config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  resources :home
  resources :storages, only: [:show]
  resources :profile
  
  root 'home#index'
  get 'home/new', to: 'home#new', as: 'home_new'
  post 'home/new', to: 'home#create'
  get 'home/show/:id', to: 'home#show', as: 'home_show'
  post 'home/:id/edit', to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
    @storage = Storage.find(params[:id])
  end

  def destroy
    @storage = Storage.find(params[:id])

    if authorize_user(@storage)
      @storage.destroy
      flash[:notice] = "Storage '#{@storage.name}' deleted."

      redirect_to '/'
    end
  end

  def update
    @storage = Storage.find(params[:id])
    
    bs = params[:storage][:book_space].to_i
  
    if bs > 0
      #Implementation to book space as an user
      @user = current_user

      puts(@user.id)
      #@user.new_booking(params[:id], bs)
      Booking.create(:booked_space => bs, :user_rating => nil, :user_id => @user.id, :storage_id => params[:id])

      new_available_space = @storage.available_space - bs
      @storage.update_attribute(:available_space, new_available_space)
           
      flash[:notice] = "#{bs} sq ft. booked in storage '#{@storage.name}' booked."
      redirect_to '/'
    else
      #Implementation to edit space as an owner 

      # Call the authorize_user method to check if the current user is authorized
      if authorize_user(@storage)
        old_name = @storage.name
        if @storage.update_attributes(storage_params)
          flash[:notice] = "'#{old_name}' updated."
          redirect_to '/'
        else
          invalid_params(@storage)
          redirect_to edit_home_path(@storage)
        end
      end
    end
  end
  
  def edit
    @storage = Storage.find(params[:id])
    authorize_user(@storage)
  end

  def clear_sort_and_filter_session
    session[:sort_by] = nil
    session[:sort_direction] = nil
    session[:min_available_space] = nil
    session[:max_price_per_sqft] = nil
    session[:max_distance_from_campus] = nil
  end

  def new
    # Clear sorting and filtering parameters from session
    clear_sort_and_filter_session
  end

  def create
    clear_sort_and_filter_session
    @storage = Storage.new(storage_params)
    @storage.user = current_user

    if @storage.valid?
      @storage.save
      flash[:notice] = "#{@storage.name} was successfully created."
      redirect_to '/'
    else
      if @storage.errors.any?
        invalid_params(@storage)
      end
      render :new
    end
  end

  def authorize_user(storage)
    if current_user != storage.user
      flash[:notice] = "You are not authorized to edit/delete this storage"
      redirect_to '/'
      return false
    end
    return true 
  end

  def index
    @storages = Storage.all
    @storages = Storage.where.not(available_space: 0.0)

    # Preserve sorting parameters if present
    @sort_by = params[:sort_by] || 'name' # Default sorting column
    @sort_direction = params[:sort_direction] || 'asc' # Default sorting direction

    # Apply sorting
    @storages = sort_storages(@storages, @sort_by, @sort_direction)

    # Get filter criteria
    @min_available_space = params[:min_available_space]
    @max_price_per_sqft = params[:max_price_per_sqft]
    @max_distance_from_campus = params[:max_distance_from_campus]

    # Apply filters if criteria are present
    if @min_available_space.present?
      min_available_space = @min_available_space.to_f
      @storages = @storages.where('available_space >= ?', min_available_space)
    end

    if @max_price_per_sqft.present?
      max_price_per_sqft = @max_price_per_sqft.to_f
      @storages = @storages.where('price <= ?', max_price_per_sqft)
    end

    if @max_distance_from_campus.present?
      max_distance_from_campus = @max_distance_from_campus.to_f
      @storages = @storages.where('campus_dist <= ?', max_distance_from_campus)
    end

    # Store sorting parameters in session
    session[:sort_by] = @sort_by
    session[:sort_direction] = @sort_direction

    # Store filter criteria in session
    session[:min_available_space] = @min_available_space
    session[:max_price_per_sqft] = @max_price_per_sqft
    session[:max_distance_from_campus] = @max_distance_from_campus
  end

 

  def sort_storages(storages, sort_by, sort_direction)
    case sort_by
    when 'name'
      storages.order!(name: sort_direction)
    when 'available_space'
      storages.order!(available_space: sort_direction)
    when 'price'
      storages.order!(price: sort_direction)
    when 'start_date'
      storages.order!(start_date: sort_direction)
    when 'end_date'
      storages.order!(end_date: sort_direction)
    when 'campus_dist'
      storages.order!(campus_dist: sort_direction)
    when 'rating'
      storages.order!(rating: sort_direction)
    end

    storages
  end

  private
  def storage_params
    params.require(:storage).permit(:name, :available_space, :price, :campus_dist, :rating, :start_date, :end_date, :image)
  end

  def invalid_params(st)
    if st.errors.any?
      st.errors.full_messages.each do |msg|
       flash[:notice] = msg
      end
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit.html.erb
<h2>Edit Existing Storage</h2>
<%= form_tag home_path(@storage), :method => :put do %>

  <%= label :storage, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :storage, :name, :class => 'form-control' %>
    
  <%= label :storage, :available_space, 'Available Space (in Sq. ft.)', :class => 'col-form-label' %>
  <%= text_field :storage, :available_space, :class => 'form-control' %>
  
  <%= label :storage, :price, 'Price per Sq. ft. (in $)', :class => 'col-form-label' %>
  <%= text_field :storage, :price, :class => 'form-control' %>

  <%= label :storage, :campus_dist, 'Distance from Campus (in Miles)', :class => 'col-form-label' %>
  <%= text_field :storage, :campus_dist, :class => 'form-control' %>
  
  <br/>
  <%= label :storage, :start_date, 'Availability Start Date', :class => 'col-form-label'  %>
  <%= date_field :storage, :start_date, :class => 'form-control' %>
  <br/>
  <%= label :storage, :end_date, 'Availability End Date', :class => 'col-form-label'  %>
   <%= date_field :storage, :end_date, :class => 'form-control' %>

  <br/>
  
   <br/>
  <%= submit_tag 'Update Storage Info', :class => 'btn btn-primary' %>

  <%= link_to 'Cancel', home_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/home/index.html.erb
<!-- This file is app/views/home/index.html.erb -->
<div class="container">
  <h2 style="margin-bottom: 30px;">All Available Storage Listings</h2>
  <div style="display:flex; justify-content:space-between; width:100%">

    <!-- Filter Section -->
    <div style="width:22%">
      <div class="filter-section">
        <%= form_tag(root_path, method: :get, class: 'filter-form') do %>
          <%= hidden_field_tag :sort_by, session[:sort_by] %>
          <%= hidden_field_tag :sort_direction, session[:sort_direction] %>

          <div class="form-group">
            <%= label_tag 'Min Space (Sq ft)' %>
            <%= number_field_tag :min_available_space, params[:min_available_space], min: 0, class: 'form-control', placeholder: 'Min Available Space' %>
          </div>

          <div class="form-group">
            <%= label_tag 'Max Price (in $)' %>
            <%= number_field_tag :max_price_per_sqft, params[:max_price_per_sqft], min: 0, step: 0.01, class: 'form-control', placeholder: 'Max Price per Sq ft' %>
          </div>

          <div class="form-group">
            <%= label_tag 'Max Distance (Miles)' %>
            <%= number_field_tag :max_distance_from_campus, params[:max_distance_from_campus], min: 0, step: 0.01, class: 'form-control', placeholder: 'Max Distance to Campus' %>
          </div>

          <%= submit_tag 'Apply Filters', class: 'btn btn-primary btn-block' %>
        <% end %>

        <div style="margin-top:5%"></div>

        <%= button_to 'Clear All', root_path, method: :get, params: { min_available_space: nil, max_price_per_sqft: nil,  max_distance_from_campus: nil}, class: 'btn btn-secondary btn-block' %>
        <div style="margin-top:20%"></div>
        <%= link_to 'Add new storage', home_new_path, :class => 'btn btn-primary' %>
      </div>
    </div>

    <!-- Sorting Options -->
    <div style="width:60%; margin-left:25px; margin-right:50px;">
      <h5>Sort Listings by:</h5>
      <table class="table table-striped" id="storages">
        <thead>
          <tr>
            <th><%= sortable_link('name', 'Address') %></th>
            <th><%= sortable_link('available_space', 'Space (Sq ft)') %></th>
            <th><%= sortable_link('price', 'Price per Sq ft') %></th>
            <th><%= sortable_link('start_date', 'Start Date') %></th>
            <th><%= sortable_link('end_date', 'End Date') %></th>
            <th><%= sortable_link('campus_dist', 'Distance to Campus (Miles)') %></th>
            <th><%= sortable_link('rating', 'Rating') %></th>
          </tr>
        </thead>
      </table>

      <!-- Data Table -->
      <% @storages.each do |storage| %>
        <div style="display:flex; flex-direction:row; margin-bottom: 15px; background-color:rgba(255, 255, 255, 0.8); border-radius:10px; box-shadow: 2px 2px 5px rgba(0,0,0,0.2)">
          <div style="margin: 8px">
            <% if storage.image.attached? %>
              <%= image_tag storage.image, height: 175, width: 175 %>
            <% else %>
              <%= image_tag "default_icon.png", height: 175, width: 175 %>
            <% end %>
          </div>
          <div>
            <h4 style="margin-top: 10px"><%= link_to "#{storage.name}", home_show_path(storage) %></h4>
            <h6><b>Available Space: </b><%= storage.available_space %> Sq Ft &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Price: $</b><%= storage.price %> / Sq. Ft.</h6>
            <h6 style="white-space:pre;"><b>Availability: </b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Start: <%= storage.start_date %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;End: <%= storage.end_date %></h6>
            <h6><b>Distance from Campus: </b><%= storage.campus_dist %> Miles</h6>
            <h6><b>Rating: </b><%= storage.rating %></h6>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/new.html.erb
<h2>Create New Storage Listing</h2>
<h6>Please enter all the details to the sotrage space you would like to rent out.</h6>

<%= form_with url: home_new_path, model: @storage, :class => 'form' do |fm| %>
  <%= fm.fields_for :storage do |f| %>

  <%= label :storage, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :storage, :name, :class => 'form-control', placeholder: 'Enter Address of the Storage Space' %>
    
  <%= label :storage, :available_space, 'Available Storage Space (in Sq. ft.)', :class => 'col-form-label' %>
  <%= text_field :storage, :available_space, :class => 'form-control', placeholder: 'Enter Available Storage Space (in Sq. ft.)' %>
  
  <%= label :storage, :price, 'Price per Sq. ft. (in $)', :class => 'col-form-label' %>
  <%= text_field :storage, :price, :class => 'form-control', placeholder: 'Price per Sq. ft. (in $)'%>

  <%= label :storage, :campus_dist, 'Distance from Campus (in Miles)', :class => 'col-form-label' %>
  <%= text_field :storage, :campus_dist, :class => 'form-control', placeholder: 'Distance from Campus (in Miles)' %>

  <%= label :storage, :start_date, 'Availability Start Date', :class => 'col-form-label'  %>
  <%= date_field :storage, :start_date, :class => 'form-control', placeholder: 'Availability Start Date' %>

  <%= label :storage, :end_date, 'Availability End Date', :class => 'col-form-label'  %>
  <%= date_field :storage, :end_date, :class => 'form-control', placeholder: 'Availability End Date' %>

  <br/>

  <%= f.label :image, 'Upload an Image of the Storage Space: ', :class => 'col-form-label'  %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.file_field :image %>
  <br/>
  <br/>
 
  <%= submit_tag 'Save', :class => "col-md-2 btn btn-success"%>
  <%= link_to 'Cancel', '/', :class => 'btn btn-secondary' %>
<% end %>

  <% end %>

app/views/home/show.html.erb
<h2>Details about <em><%= @storage.name %></em></h2>


<div class="container" style =  "margin-top: 30px;">
<div style="width:40%;  float: right;">
<% if @storage.image.attached? %>
  <%= image_tag @storage.image, height: 400, width: 400 %>
<% else %>
  <%= image_tag "default_icon.png", height: 400, width: 400 %>
<% end %>
</div>

<div style = "width:60%; margin-right: 20px;">
<ul id="details">
  <li>
    Name:
    <%= @storage.name %>
  </li>
  <li>
   Available Space (in Sq. ft.):
   <%= @storage.available_space %>
  </li>
  <li>
    Price per Sq. ft. (in $):
    <%= @storage.price%>
  </li>
  <li>
   Distance from Campus:
    <%= @storage.campus_dist%>
  </li>
   <li>
   Rating:
    <%= @storage.rating%>
  </li>
   <li>
    Availability Start Date:
    <%= @storage.start_date.strftime("%B %d, %Y") %>
  </li>
   <li>
    Availability End Date:
    <%= @storage.end_date.strftime("%B %d, %Y") %>
  </li>
</ul>

</div>

<div>

  <%= form_for @storage, url: home_path(@storage), method: :patch do |f| %>
    Book Space (in sq. ft.): <%= f.number_field :book_space, min: 1, max: @storage.available_space, id: 'book-space-input' %>
    <%= f.submit "Confirm Booking", :class => "col-md-2 btn btn-success"%>
  <% end %>

  <br/>

  <div id="estimated-price-section">
    <p>Estimated Total Price: $<span id="estimated-total-price">0.00</span></p>
  </div>
  <br/>
  <div>
  <%= link_to 'Edit', edit_home_path(@storage), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', home_path(@storage), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
 </div>
</div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var pricePerSqFt = <%= @storage.price %>;

        // Update estimated total price on input change
        document.getElementById('book-space-input').addEventListener('input', function() {
            var enteredSqFt = this.value;
            var estimatedPrice = enteredSqFt * pricePerSqFt;
            document.getElementById('estimated-total-price').innerText = estimatedPrice.toFixed(2);
        });
    });
</script>